server:
  port: ${SERVER_PORT}

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%X{correlationId}] %-5level %logger{36} - %msg%n"

spring:
  application:
    name: ${APP_NAME}

  #  DATABASES 
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASS}

  keycloak-datasource:
    url: jdbc:postgresql://${KEYCLOAK_DB_HOST}:${KEYCLOAK_DB_PORT}/${KEYCLOAK_DB_NAME}
    username: ${KEYCLOAK_DB_USER}
    password: ${KEYCLOAK_DB_PASS}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
      jakarta:
        persistence:
          validation:
            mode: none

  #  SECURITY & AUTH 
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_SERVER_URL}/realms/${KEYCLOAK_REALM}
          jwk-set-uri: ${KEYCLOAK_SERVER_URL}/realms/${KEYCLOAK_REALM}/protocol/openid-connect/certs

  #  MESSAGE BROKER 
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
    virtual-host: /

  #  LDAP 
  ldap:
    urls: ${LDAP_URLS}
    base: ${LDAP_BASE}
    username: ${LDAP_USERNAME}
    password: ${LDAP_PASSWORD}
    base-environment:
      java.naming.ldap.attributes.binary: entryUUID

  #  EMAIL 
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  #  WEB & SERVLET 
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

#  SERVICE DISCOVERY 
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL}

#  CUSTOM PROPERTIES 
keycloak:
  server-url: ${KEYCLOAK_SERVER_URL}
  external-url: ${KEYCLOAK_EXTERNAL_URL}
  realm: ${KEYCLOAK_REALM}
  client-id: ${KEYCLOAK_CLIENT_ID}
  client-secret: ${KEYCLOAK_CLIENT_SECRET}
  ldap-provider-id: ${KEYCLOAK_LDAP_ID}

r2:
  endpoint: ${R2_ENDPOINT}
  public-url: ${R2_PUBLIC_URL}
  access-key: ${R2_ACCESS_KEY}
  secret-key: ${R2_SECRET_KEY}
  bucket-name: ${R2_BUCKET_NAME}

#  DOCUMENTATION 
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs

opa:
  url: ${OPA_URL:http://localhost:8181}